# Part 4 -- Combine Features and Target (SP500)

Since our feature data (Tweets) and target data (stocks) are pulled from different sources and have different numbers of rows and columns, we will need to do some cleaning to make sure our X's and y's share the same number of rows. This is important for when we feed our data into models.

**Load lib codes**

In [1]:
from os import chdir
chdir('/home/jovyan/work/Portfolio/Analyzing_Unstructured_Data_for_Finance/')

from lib import *
# suppress_warnings()

In [5]:
SP500_df = pd.read_pickle('../Analyzing_Unstructured_Data_for_Finance/data/3.2.sp500_stocks_df.pickle')

In [3]:
tweets_df = pd.read_pickle('../Analyzing_Unstructured_Data_for_Finance/data/2.tweets_df.pickle')

In [6]:
SP500_df.shape

(2014, 9)

In [6]:
tweets_df.shape

(94856, 6)

**Do some checks to see if everything matches correctly before merging the dataframes**

In [11]:
SP500_df

,Date,Close,Diff,High,Low,Open,Percent_Change,Volume,Percent_Change_Class
0,2009-06-11,32.667335,NaN,33.265558,32.216560,32.561025,NaN,9.099051e+06,None
1,2009-06-12,32.688793,0.021458,32.960957,31.988679,32.498793,0.001143,7.448299e+06,down
2,2009-06-15,31.817836,-0.870957,32.497790,31.478018,32.321503,-0.029037,7.741524e+06,down
3,2009-06-16,31.376720,-0.441116,32.295763,31.180159,32.013235,-0.015482,8.076007e+06,down
4,2009-06-17,31.300774,-0.075945,31.859841,30.772847,31.321162,-0.002832,9.228160e+06,down
5,2009-06-18,31.549681,0.248907,31.922210,30.976287,31.367244,0.007020,7.615357e+06,up
6,2009-06-19,31.668702,0.119021,32.167198,31.296651,31.850296,0.005157,1.007858e+07,neutral
7,2009-06-22,30.605786,-1.062916,31.563280,30.417631,31.316059,-0.037623,8.669310e+06,down
8,2009-06-23,30.605945,0.000159,31.070182,30.183098,30.703280,-0.000601,8.319911e+06,down
9,2009-06-24,30.897722,0.291777,31.412551,30.460000,30.801276,0.010428,7.879481e+06,up
10,2009-06-25,31.590501,0.692779,31.760410,30.539841,30.781822,0.023472,8.458110e+06,up
11,2009-06-26,31.597289,0.006788,31.920319,31.109362,31.480979,0.000314,8.792982e+06,down
12,2009-06-29,31.809613,0.212323,32.114237,31.259544,31.682916,0.007211,6.732848e+06,up
13,2009-06-30,31.589544,-0.220068,32.111298,31.178178,31.816902,-0.006819,8.185126e+06,down
14,2009-07-01,31.738178,0.148633,32.249385,31.400410,31.766059,0.005933,6.836343e+06,up
15,2009-07-02,30.725034,-1.013144,31.563895,30.546743,31.336697,-0.034895,6.816053e+06,down
16,2009-07-06,30.818838,0.093804,31.067175,30.104920,30.513235,0.000732,7.692075e+06,down
17,2009-07-07,30.082050,-0.736788,31.006492,29.950797,30.768952,-0.025772,7.813058e+06,down
18,2009-07-08,30.022050,-0.060000,30.557016,29.498542,30.225558,-0.003689,1.042979e+07,down
19,2009-07-09,30.185718,0.163667,30.650137,29.808269,30.260979,0.004954,7.289074e+06,neutral
20,2009-07-10,30.090068,-0.095649,30.467358,29.624510,29.985080,-0.002170,6.414542e+06,down
21,2009-07-13,30.843030,0.752961,30.925262,29.761617,30.200319,0.024986,8.116054e+06,up
22,2009-07-14,31.073075,0.230046,31.285604,30.501025,30.873554,0.007774,6.815414e+06,up
23,2009-07-15,31.966629,0.893554,32.157426,31.181526,31.426765,0.029812,9.324004e+06,up
24,2009-07-16,32.347153,0.380524,32.561936,31.526333,31.852255,0.011061,7.623406e+06,up
25,2009-07-17,32.218542,-0.128610,32.600319,31.803576,32.285945,-0.004050,7.966149e+06,down
26,2009-07-20,32.744989,0.526446,32.954419,32.080797,32.411207,0.016619,7.679517e+06,up
27,2009-07-21,32.811595,0.066606,33.252528,32.229909,32.954351,0.000022,8.360475e+06,down
28,2009-07-22,32.877859,0.066264,33.276743,32.313781,32.608929,0.003131,8.772734e+06,down
29,2009-07-23,33.925626,1.047768,34.228246,32.688246,32.952369,0.030053,1.059629e+07,up
...,...,...,...,...,...,...,...,...,...
1984,2017-04-28,96.742515,-0.176467,97.730978,96.075529,97.164790,-0.005054,4.457278e+06,down
1985,2017-05-01,96.850120,0.107605,97.660938,96.150659,96.930339,-0.000659,3.760106e+06,down
1986,2017-05-02,97.162994,0.312874,97.751617,96.278942,97.016367,0.000984,4.779064e+06,down
1987,2017-05-03,96.953832,-0.209162,97.672515,96.168423,97.033194,-0.003714,4.514684e+06,down
1988,2017-05-04,97.245908,0.292076,97.954271,96.273054,97.081936,0.000179,4.448414e+06,down
1989,2017-05-05,97.698942,0.453034,98.182814,96.811477,97.520000,0.006252,3.621677e+06,up
1990,2017-05-08,97.483453,-0.215489,98.226747,96.878463,97.682655,-0.002473,3.636687e+06,down
1991,2017-05-09,97.511677,0.028224,98.188862,96.887485,97.571138,-0.000581,3.713818e+06,down
1992,2017-05-10,97.525010,0.013333,98.083014,96.687984,97.407924,0.003128,3.935017e+06,down
1993,2017-05-11,97.262894,-0.262116,97.810200,96.328563,97.243074,-0.004593,4.017858e+06,down
1994,2017-05-12,96.974152,-0.288743,97.666966,96.464391,97.170140,-0.004788,3.569796e+06,down
1995,2017-05-15,97.509401,0.535250,98.033693,96.705808,97.093393,0.005793,3.787458e+06,up
1996,2017-05-16,97.383313,-0.126088,98.099621,96.780459,97.658204,-0.002993,4.067815e+06,down
1997,2017-05-17,95.783234,-1.600080,97.303992,95.407605,96.615509,-0.016849,5.404614e+06,down
1998,2017-05-18,96.206707,0.423473,96.915130,95.100259,95.726168,0.002639,4.634264e+06,down
1999,2017-05-19,96.858543,0.651836,97.512575,95.959301,96.513253,0.007667,4.477392e+06,up
2000,2017-05-22,97.444651,0.586108,97.975369,96.590958,97.107944,0.005277,3.692048e+06,neutral
2001,2017-05-23,97.311697,-0.132954,98.053313,96.650339,97.431218,-0.000309,3.514729e+06,down
2002,2017-05-24,97.643273,0.331577,98.136727,96.762176,97.410639,0.001673,3.571004e+06,down
2003,2017-05-25,98.260000,0.616727,98.941357,97.348224,97.950379,0.003405,4.014203e+06,down
2004,2017-05-26,98.282655,0.022655,98.837505,97.663014,98.257665,-0.000145,3.026608e+06,down
2005,2017-05-30,98.125689,-0.156966,98.733234,97.516128,98.087725,-0.002293,3.522117e+06,down
2006,2017-05-31,98.249002,0.123313,98.847705,97.313433,98.260719,0.000393,5.184513e+06,down
2007,2017-06-01,99.185749,0.936747,99.571517,97.842435,98.457345,0.010676,4.236422e+06,up
2008,2017-06-02,99.579461,0.393713,100.139122,98.657305,99.334431,0.000860,4.021522e+06,down
2009,2017-06-05,99.356886,-0.222575,100.097026,98.786008,99.493433,-0.002752,3.463113e+06,down
2010,2017-06-06,98.913832,-0.443054,99.790878,98.366826,99.113932,-0.003828,3.947967e+06,down
2011,2017-06-07,99.065110,0.151277,99.712216,98.322934,99.056806,0.000184,4.151218e+06,down
2012,2017-06-08,99.107844,0.042735,99.863034,98.246547,99.133174,0.000821,4.480758e+06,down
2013,2017-06-09,98.932894,-0.174950,100.213992,97.646367,99.212695,0.004178,5.230035e+06,down

In [8]:
tweets_df.head()

,_id,text,timestamp,username,Date,cleaned_text
0,593deb7057bbd4047664223e,"On this National Gun Violence Awareness Day, l...",2017-06-02 17:35:54,BarackObama,2017-06-02,on this national gun violence awareness day le...
1,593deb7057bbd4047664223f,Forever grateful for the service and sacrifice...,2017-05-29 13:09:16,BarackObama,2017-05-29,forever grateful for the service and sacrifice...
2,593deb7057bbd40476642240,Good to see my friend Prince Harry in London t...,2017-05-27 13:15:25,BarackObama,2017-05-27,good to see my friend prince harry in london t...
3,593deb7057bbd40476642241,"Through faith, love, and resolve the character...",2017-05-25 14:13:35,BarackObama,2017-05-25,through faith love and resolve the character o...
4,593deb7057bbd40476642242,Our hearts go out to those killed and wounded ...,2017-05-23 16:56:14,BarackObama,2017-05-23,our hearts go out to those killed and wounded ...

In [10]:
tweets_df['Date'][3]==AAPL_df['Date'][2002]

True

In [13]:
AAPL_df[AAPL_df['Percent_Change_Class']=='neutral']

,Date,Open,High,Low,Close,Volume,Diff,Percent_Change,Percent_Change_Class
18,2009-07-08,19.42,19.72,19.20,19.60,143982048,0.26,0.013265,neutral
26,2009-07-20,21.90,22.15,21.56,21.84,183881187,0.16,0.007326,neutral
29,2009-07-23,22.38,22.63,22.22,22.55,131740378,0.16,0.007095,neutral
30,2009-07-24,22.42,22.86,22.36,22.86,109589914,0.31,0.013561,neutral
40,2009-08-07,23.64,23.80,23.54,23.64,96870928,0.22,0.009306,neutral
49,2009-08-20,23.57,23.82,23.52,23.76,85549730,0.25,0.010522,neutral
54,2009-08-27,24.11,24.22,23.55,24.21,112294826,0.29,0.011979,neutral
59,2009-09-03,23.78,23.87,23.57,23.79,73525711,0.19,0.007987,neutral
61,2009-09-08,24.71,24.73,24.57,24.70,78761627,0.37,0.014980,neutral
63,2009-09-10,24.58,24.75,24.40,24.65,122783346,0.20,0.008114,neutral
65,2009-09-14,24.40,24.84,24.32,24.82,80502611,0.23,0.009267,neutral
66,2009-09-15,24.86,25.09,24.80,25.02,106617553,0.20,0.007994,neutral
68,2009-09-17,26.00,26.68,26.00,26.36,202642664,0.38,0.014416,neutral
72,2009-09-23,26.49,26.99,26.43,26.50,148509963,0.15,0.005660,neutral
80,2009-10-05,26.60,26.69,26.32,26.57,105783062,0.16,0.006022,neutral
84,2009-10-09,27.00,27.24,26.95,27.21,73348345,0.17,0.006248,neutral
87,2009-10-14,27.46,27.47,27.18,27.33,93942639,0.18,0.006586,neutral
90,2009-10-19,26.84,27.14,26.51,27.12,235557336,0.26,0.009587,neutral
102,2009-11-04,27.25,27.69,27.18,27.26,121935499,0.30,0.011005,neutral
106,2009-11-10,28.72,29.28,28.72,29.00,100298380,0.22,0.007586,neutral
109,2009-11-13,28.98,29.26,28.87,29.21,85832761,0.35,0.011982,neutral
110,2009-11-16,29.35,29.71,29.29,29.52,121301019,0.31,0.010501,neutral
129,2009-12-14,27.91,28.20,27.51,28.14,123947124,0.33,0.011727,neutral
134,2009-12-21,28.01,28.54,27.95,28.32,153093108,0.40,0.014124,neutral
135,2009-12-22,28.49,28.69,28.38,28.62,87378543,0.30,0.010482,neutral
136,2009-12-23,28.75,28.91,28.69,28.87,86380987,0.25,0.008660,neutral
138,2009-12-28,30.25,30.56,29.94,30.23,161141050,0.37,0.012239,neutral
140,2009-12-30,29.83,30.29,29.76,30.23,103020708,0.36,0.011909,neutral
146,2010-01-08,30.04,30.29,29.87,30.28,111969081,0.20,0.006605,neutral
149,2010-01-13,29.70,30.13,29.16,30.09,151472335,0.42,0.013958,neutral
...,...,...,...,...,...,...,...,...,...
1886,2016-12-07,109.26,111.19,109.16,111.03,29998719,1.08,0.009727,neutral
1887,2016-12-08,110.86,112.43,110.60,112.12,27068316,1.09,0.009722,neutral
1892,2016-12-15,115.38,116.73,115.23,115.82,46524544,0.63,0.005439,neutral
1894,2016-12-19,115.80,117.38,115.75,116.64,27779423,0.67,0.005744,neutral
1899,2016-12-27,116.52,117.80,116.49,117.26,18296855,0.74,0.006311,neutral
1905,2017-01-05,115.92,116.86,115.81,116.61,22193587,0.59,0.005060,neutral
1906,2017-01-06,116.78,118.16,116.47,117.91,31751900,1.30,0.011025,neutral
1907,2017-01-09,117.95,119.43,117.94,118.99,33561948,1.08,0.009076,neutral
1909,2017-01-11,118.74,119.93,118.60,119.75,27588593,0.64,0.005344,neutral
1912,2017-01-17,118.34,120.24,118.22,120.00,34439843,0.96,0.008000,neutral
1926,2017-02-06,129.13,130.50,128.90,130.29,26845924,1.21,0.009287,neutral
1927,2017-02-07,130.54,132.09,130.45,131.53,38183841,1.24,0.009428,neutral
1931,2017-02-13,133.08,133.82,132.75,133.29,23035421,1.17,0.008778,neutral
1932,2017-02-14,133.47,135.09,133.25,135.02,33226223,1.73,0.012813,neutral
1936,2017-02-21,136.23,136.75,135.98,136.70,24507156,0.98,0.007169,neutral
1944,2017-03-03,138.78,139.83,138.59,139.78,21571121,0.82,0.005866,neutral
1952,2017-03-15,139.41,140.75,139.02,140.46,25691774,1.47,0.010466,neutral
1955,2017-03-20,140.40,141.50,140.23,141.46,21542038,1.47,0.010392,neutral
1957,2017-03-22,139.84,141.60,139.76,141.42,25860165,1.58,0.011172,neutral
1966,2017-04-04,143.25,144.89,143.17,144.77,19891354,1.07,0.007391,neutral
1974,2017-04-17,141.48,141.88,140.87,141.83,16582094,0.78,0.005500,neutral
1977,2017-04-20,141.22,142.92,141.16,142.44,23319562,1.76,0.012356,neutral
1979,2017-04-24,143.50,143.95,143.18,143.64,17134333,1.37,0.009538,neutral
1980,2017-04-25,143.91,144.90,143.87,144.53,18871501,0.89,0.006158,neutral
1985,2017-05-02,147.54,148.09,146.84,147.51,45352194,0.93,0.006305,neutral
1990,2017-05-09,153.87,154.88,153.45,153.99,39130363,0.98,0.006364,neutral
1993,2017-05-12,154.70,156.42,154.67,156.10,32527017,2.15,0.013773,neutral
1999,2017-05-22,154.00,154.58,152.91,153.99,22966437,0.93,0.006039,neutral
2007,2017-06-02,153.58,155.45,152.89,155.45,27770715,2.27,0.014603,neutral
2010,2017-06-07,155.02,155.98,154.48,155.37,21069647,0.92,0.005921,neutral

In [15]:
AAPL_df['Percent_Change_Class'].loc[AAPL_df['Date']==dt.date(2009, 7, 8)].values

array(['neutral'], dtype=object)

In [24]:
def match_dates_and_get_stock_change(features_df, target_df):
    change = []

    for i in features_df['Date']:
        try:
            if i in list(target_df['Date']):
                change.append(target_df['Percent_Change_Class'].loc[target_df['Date']==i].values)
            elif i not in list(target_df['Date']):
                change.append('x')
                pass
        except Exception as e:
            print('Error:', e)
            
    return pd.DataFrame(change)

In [25]:
start = datetime.now()

change_df = match_dates_and_get_stock_change(tweets_df, AAPL_df)

end = datetime.now()
print(end - start)

0:01:03.680343

In [26]:
change_df[0].value_counts()

down       54061
x          17573
neutral    16515
up          6707
Name: 0, dtype: int64

In [19]:
54061+17573+16515+6707

94856

**Now, we have our X's and y's**<br>
Our <u>Features</u> == Tweets (\_id, text, timestamp, username, cleaned_text, Date)<br>
Our <u>Target</u> == change in stock prices (up/down/neutral)<br>

They have the same number of rows and are in the same order, so our X and Y's are ready! Now, we just need to drop the rows where our X's and y's don't have a Date in common.

**Merge & drop rows where there's no stock data for Tweets**

In [27]:
combined_df_nodrop = tweets_df.merge(change_df, left_index=True, right_index=True)

In [31]:
combined_df_nodrop.head(5)

,_id,text,timestamp,username,Date,cleaned_text,0
0,593deb7057bbd4047664223e,"On this National Gun Violence Awareness Day, l...",2017-06-02 17:35:54,BarackObama,2017-06-02,on this national gun violence awareness day le...,neutral
1,593deb7057bbd4047664223f,Forever grateful for the service and sacrifice...,2017-05-29 13:09:16,BarackObama,2017-05-29,forever grateful for the service and sacrifice...,x
2,593deb7057bbd40476642240,Good to see my friend Prince Harry in London t...,2017-05-27 13:15:25,BarackObama,2017-05-27,good to see my friend prince harry in london t...,x
3,593deb7057bbd40476642241,"Through faith, love, and resolve the character...",2017-05-25 14:13:35,BarackObama,2017-05-25,through faith love and resolve the character o...,down
4,593deb7057bbd40476642242,Our hearts go out to those killed and wounded ...,2017-05-23 16:56:14,BarackObama,2017-05-23,our hearts go out to those killed and wounded ...,down

In [29]:
combined_df = combined_df_nodrop[combined_df_nodrop[0]!='x']

In [32]:
combined_df.head(5)

,_id,text,timestamp,username,Date,cleaned_text,0
0,593deb7057bbd4047664223e,"On this National Gun Violence Awareness Day, l...",2017-06-02 17:35:54,BarackObama,2017-06-02,on this national gun violence awareness day le...,neutral
3,593deb7057bbd40476642241,"Through faith, love, and resolve the character...",2017-05-25 14:13:35,BarackObama,2017-05-25,through faith love and resolve the character o...,down
4,593deb7057bbd40476642242,Our hearts go out to those killed and wounded ...,2017-05-23 16:56:14,BarackObama,2017-05-23,our hearts go out to those killed and wounded ...,down
5,593deb7057bbd40476642243,"Excited to hear from Sierra, Imani, Filiz, and...",2017-05-22 21:16:23,BarackObama,2017-05-22,excited to hear from sierra imani filiz and be...,neutral
7,593deb7057bbd40476642245,"We're rolling up our sleeves again, back where...",2017-05-03 19:42:16,BarackObama,2017-05-03,we re rolling up our sleeves again back where ...,down

In [33]:
pd.to_pickle(combined_df, '../Analyzing_Unstructured_Data_for_Finance/data/4.1.combined_df_AAPL.pickle')

**Now split the data into X's and y's - our features and target**

In [34]:
X = combined_df.drop(0, axis=1)
y = combined_df[0]

In [35]:
print(X.shape)
print(y.shape)

(77283, 6)
(77283,)

In [36]:
77283.0/94856.0
# We kept 81% of original tweets (after dropping ones that don't match)

0.8147402378341908

In [37]:
pd.to_pickle(X, '../Analyzing_Unstructured_Data_for_Finance/data/4.1.X.pickle')

In [38]:
pd.to_pickle(y, '../Analyzing_Unstructured_Data_for_Finance/data/4.1.y_AAPL.pickle')

In [39]:
combined_df[0].value_counts()

down       54061
neutral    16515
up          6707
Name: 0, dtype: int64