# Part 4 -- Get Target Data

Get stock data for S&P 500 using **pandas**.

### Load lib codes:

In [1]:
!pwd

/home/jovyan/work/Portfolio/predicting_stock_market_trends_with_Twitter/ipynb

In [2]:
from os import chdir
chdir('/home/jovyan/work/Portfolio/predicting_stock_market_trends_with_Twitter/')

from lib import *
# suppress_warnings()
from lib.twitter_keys import my_keys

In [43]:
import datetime as dt
import pandas_datareader.data as web
import bs4 as bs
import pickle
import requests

In [194]:
start = dt.datetime(2008,1,1)
end = dt.datetime(2017,6,1)
AAPL_df = web.DataReader('AAPL', 'google', start, end)

In [195]:
AAPL_df = AAPL_df.reset_index()

In [196]:
AAPL_df

           Date    Open    High     Low   Close     Volume
0    2008-01-02   28.47   28.61   27.51   27.83  269794140
1    2008-01-03   27.92   28.20   27.53   27.85  210516460
2    2008-01-04   27.35   27.57   25.56   25.72  363888854
3    2008-01-07   25.89   26.23   24.32   25.38  518047922
4    2008-01-08   25.73   26.07   24.40   24.46  380953888
5    2008-01-09   24.50   25.60   24.00   25.60  453884711
6    2008-01-10   25.37   25.86   25.06   25.43  370743450
7    2008-01-11   25.14   25.41   24.29   24.67  307982640
8    2008-01-14   25.36   25.63   25.02   25.54  275112418
9    2008-01-15   25.39   25.60   23.52   24.15  585814124
10   2008-01-16   23.62   24.14   22.39   22.81  554343923
11   2008-01-17   23.07   23.62   22.63   22.98  439973891
12   2008-01-18   23.10   23.68   22.80   23.05  430907932
13   2008-01-22   21.15   22.85   20.86   22.23  608744360
14   2008-01-23   19.46   20.00   18.02   19.87  843264044
15   2008-01-24   20.00   20.10   18.86   19.37  501466091
16   2008-01-25   19.86   19.87   18.52   18.57  388684198
17   2008-01-28   18.31   19.03   18.06   18.57  368710818
18   2008-01-29   18.74   18.97   18.44   18.79  274995602
19   2008-01-30   18.77   19.35   18.57   18.88  310762333
20   2008-01-31   18.49   19.52   18.49   19.34  336417991
21   2008-02-01   19.46   19.51   18.88   19.11  252653079
22   2008-02-04   19.17   19.41   18.77   18.81  224808367
23   2008-02-05   18.63   19.14   18.41   18.48  285260437
24   2008-02-06   18.69   18.85   17.40   17.43  393317435
25   2008-02-07   17.14   17.83   16.75   17.32  521151925
26   2008-02-08   17.44   17.96   17.37   17.93  338930627
27   2008-02-11   18.29   18.57   18.17   18.49  300357519
28   2008-02-12   18.67   18.71   17.66   17.84  306494601
29   2008-02-13   18.10   18.54   17.95   18.49  242133283
...         ...     ...     ...     ...     ...        ...
2340 2017-04-20  141.22  142.92  141.16  142.44   23319562
2341 2017-04-21  142.44  142.68  141.85  142.27   17320928
2342 2017-04-24  143.50  143.95  143.18  143.64   17134333
2343 2017-04-25  143.91  144.90  143.87  144.53   18871501
2344 2017-04-26  144.47  144.60  143.38  143.68   20041241
2345 2017-04-27  143.92  144.16  143.31  143.79   14246347
2346 2017-04-28  144.09  144.30  143.27  143.65   20860358
2347 2017-05-01  145.10  147.20  144.96  146.58   33602943
2348 2017-05-02  147.54  148.09  146.84  147.51   45352194
2349 2017-05-03  145.59  147.49  144.27  147.06   45697034
2350 2017-05-04  146.52  147.14  145.81  146.53   23371872
2351 2017-05-05  146.76  148.98  146.76  148.96   27327725
2352 2017-05-08  149.03  153.70  149.03  153.01   48752413
2353 2017-05-09  153.87  154.88  153.45  153.99   39130363
2354 2017-05-10  153.63  153.94  152.11  153.26   25805692
2355 2017-05-11  152.45  154.07  152.31  153.95   27255058
2356 2017-05-12  154.70  156.42  154.67  156.10   32527017
2357 2017-05-15  156.01  156.65  155.05  155.70   26009719
2358 2017-05-16  155.94  156.06  154.72  155.47   20048478
2359 2017-05-17  153.60  154.57  149.71  150.25   50767678
2360 2017-05-18  151.27  153.34  151.13  152.54   33568215
2361 2017-05-19  153.38  153.98  152.63  153.06   26960788
2362 2017-05-22  154.00  154.58  152.91  153.99   22966437
2363 2017-05-23  154.90  154.90  153.31  153.80   19918871
2364 2017-05-24  153.84  154.17  152.67  153.34   19219154
2365 2017-05-25  153.73  154.35  153.03  153.87   19235598
2366 2017-05-26  154.00  154.24  153.31  153.61   21927637
2367 2017-05-30  153.42  154.43  153.33  153.67   20126851
2368 2017-05-31  153.97  154.17  152.38  152.76   24451164
2369 2017-06-01  153.17  153.33  152.22  153.18   16404088

[2370 rows x 6 columns]

In [197]:
AAPL_df['Diff'] = AAPL_df['Close'].diff()

In [198]:
AAPL_df

           Date    Open    High     Low   Close     Volume  Diff
0    2008-01-02   28.47   28.61   27.51   27.83  269794140   NaN
1    2008-01-03   27.92   28.20   27.53   27.85  210516460  0.02
2    2008-01-04   27.35   27.57   25.56   25.72  363888854 -2.13
3    2008-01-07   25.89   26.23   24.32   25.38  518047922 -0.34
4    2008-01-08   25.73   26.07   24.40   24.46  380953888 -0.92
5    2008-01-09   24.50   25.60   24.00   25.60  453884711  1.14
6    2008-01-10   25.37   25.86   25.06   25.43  370743450 -0.17
7    2008-01-11   25.14   25.41   24.29   24.67  307982640 -0.76
8    2008-01-14   25.36   25.63   25.02   25.54  275112418  0.87
9    2008-01-15   25.39   25.60   23.52   24.15  585814124 -1.39
10   2008-01-16   23.62   24.14   22.39   22.81  554343923 -1.34
11   2008-01-17   23.07   23.62   22.63   22.98  439973891  0.17
12   2008-01-18   23.10   23.68   22.80   23.05  430907932  0.07
13   2008-01-22   21.15   22.85   20.86   22.23  608744360 -0.82
14   2008-01-23   19.46   20.00   18.02   19.87  843264044 -2.36
15   2008-01-24   20.00   20.10   18.86   19.37  501466091 -0.50
16   2008-01-25   19.86   19.87   18.52   18.57  388684198 -0.80
17   2008-01-28   18.31   19.03   18.06   18.57  368710818  0.00
18   2008-01-29   18.74   18.97   18.44   18.79  274995602  0.22
19   2008-01-30   18.77   19.35   18.57   18.88  310762333  0.09
20   2008-01-31   18.49   19.52   18.49   19.34  336417991  0.46
21   2008-02-01   19.46   19.51   18.88   19.11  252653079 -0.23
22   2008-02-04   19.17   19.41   18.77   18.81  224808367 -0.30
23   2008-02-05   18.63   19.14   18.41   18.48  285260437 -0.33
24   2008-02-06   18.69   18.85   17.40   17.43  393317435 -1.05
25   2008-02-07   17.14   17.83   16.75   17.32  521151925 -0.11
26   2008-02-08   17.44   17.96   17.37   17.93  338930627  0.61
27   2008-02-11   18.29   18.57   18.17   18.49  300357519  0.56
28   2008-02-12   18.67   18.71   17.66   17.84  306494601 -0.65
29   2008-02-13   18.10   18.54   17.95   18.49  242133283  0.65
...         ...     ...     ...     ...     ...        ...   ...
2340 2017-04-20  141.22  142.92  141.16  142.44   23319562  1.76
2341 2017-04-21  142.44  142.68  141.85  142.27   17320928 -0.17
2342 2017-04-24  143.50  143.95  143.18  143.64   17134333  1.37
2343 2017-04-25  143.91  144.90  143.87  144.53   18871501  0.89
2344 2017-04-26  144.47  144.60  143.38  143.68   20041241 -0.85
2345 2017-04-27  143.92  144.16  143.31  143.79   14246347  0.11
2346 2017-04-28  144.09  144.30  143.27  143.65   20860358 -0.14
2347 2017-05-01  145.10  147.20  144.96  146.58   33602943  2.93
2348 2017-05-02  147.54  148.09  146.84  147.51   45352194  0.93
2349 2017-05-03  145.59  147.49  144.27  147.06   45697034 -0.45
2350 2017-05-04  146.52  147.14  145.81  146.53   23371872 -0.53
2351 2017-05-05  146.76  148.98  146.76  148.96   27327725  2.43
2352 2017-05-08  149.03  153.70  149.03  153.01   48752413  4.05
2353 2017-05-09  153.87  154.88  153.45  153.99   39130363  0.98
2354 2017-05-10  153.63  153.94  152.11  153.26   25805692 -0.73
2355 2017-05-11  152.45  154.07  152.31  153.95   27255058  0.69
2356 2017-05-12  154.70  156.42  154.67  156.10   32527017  2.15
2357 2017-05-15  156.01  156.65  155.05  155.70   26009719 -0.40
2358 2017-05-16  155.94  156.06  154.72  155.47   20048478 -0.23
2359 2017-05-17  153.60  154.57  149.71  150.25   50767678 -5.22
2360 2017-05-18  151.27  153.34  151.13  152.54   33568215  2.29
2361 2017-05-19  153.38  153.98  152.63  153.06   26960788  0.52
2362 2017-05-22  154.00  154.58  152.91  153.99   22966437  0.93
2363 2017-05-23  154.90  154.90  153.31  153.80   19918871 -0.19
2364 2017-05-24  153.84  154.17  152.67  153.34   19219154 -0.46
2365 2017-05-25  153.73  154.35  153.03  153.87   19235598  0.53
2366 2017-05-26  154.00  154.24  153.31  153.61   21927637 -0.26
2367 2017-05-30  153.42  154.43  153.33  153.67   20126851  0.06
2368 2017-05-31  153.97  154.17  152.38  152.76   24451164 -0.91
2369 2017-06-01  153.17  153.33  152.22  153.18   16404088  0.42

[2370 rows x 7 columns]

In [199]:
def make_binary(data):
    data_list = []
    for d in data:
        if d < 0:
            data_list.append(-1)
        elif d > 0:
            data_list.append(1)
        elif d == 0:
            data_list.append(0)
        else:
            data_list.append(None)
    return data_list

In [200]:
AAPL_df['Diff_Encoded'] = make_binary(AAPL_df['Diff'])

In [201]:
AAPL_df

           Date    Open    High     Low   Close     Volume  Diff  Diff_Encoded
0    2008-01-02   28.47   28.61   27.51   27.83  269794140   NaN           NaN
1    2008-01-03   27.92   28.20   27.53   27.85  210516460  0.02           1.0
2    2008-01-04   27.35   27.57   25.56   25.72  363888854 -2.13          -1.0
3    2008-01-07   25.89   26.23   24.32   25.38  518047922 -0.34          -1.0
4    2008-01-08   25.73   26.07   24.40   24.46  380953888 -0.92          -1.0
5    2008-01-09   24.50   25.60   24.00   25.60  453884711  1.14           1.0
6    2008-01-10   25.37   25.86   25.06   25.43  370743450 -0.17          -1.0
7    2008-01-11   25.14   25.41   24.29   24.67  307982640 -0.76          -1.0
8    2008-01-14   25.36   25.63   25.02   25.54  275112418  0.87           1.0
9    2008-01-15   25.39   25.60   23.52   24.15  585814124 -1.39          -1.0
10   2008-01-16   23.62   24.14   22.39   22.81  554343923 -1.34          -1.0
11   2008-01-17   23.07   23.62   22.63   22.98  439973891  0.17           1.0
12   2008-01-18   23.10   23.68   22.80   23.05  430907932  0.07           1.0
13   2008-01-22   21.15   22.85   20.86   22.23  608744360 -0.82          -1.0
14   2008-01-23   19.46   20.00   18.02   19.87  843264044 -2.36          -1.0
15   2008-01-24   20.00   20.10   18.86   19.37  501466091 -0.50          -1.0
16   2008-01-25   19.86   19.87   18.52   18.57  388684198 -0.80          -1.0
17   2008-01-28   18.31   19.03   18.06   18.57  368710818  0.00           0.0
18   2008-01-29   18.74   18.97   18.44   18.79  274995602  0.22           1.0
19   2008-01-30   18.77   19.35   18.57   18.88  310762333  0.09           1.0
20   2008-01-31   18.49   19.52   18.49   19.34  336417991  0.46           1.0
21   2008-02-01   19.46   19.51   18.88   19.11  252653079 -0.23          -1.0
22   2008-02-04   19.17   19.41   18.77   18.81  224808367 -0.30          -1.0
23   2008-02-05   18.63   19.14   18.41   18.48  285260437 -0.33          -1.0
24   2008-02-06   18.69   18.85   17.40   17.43  393317435 -1.05          -1.0
25   2008-02-07   17.14   17.83   16.75   17.32  521151925 -0.11          -1.0
26   2008-02-08   17.44   17.96   17.37   17.93  338930627  0.61           1.0
27   2008-02-11   18.29   18.57   18.17   18.49  300357519  0.56           1.0
28   2008-02-12   18.67   18.71   17.66   17.84  306494601 -0.65          -1.0
29   2008-02-13   18.10   18.54   17.95   18.49  242133283  0.65           1.0
...         ...     ...     ...     ...     ...        ...   ...           ...
2340 2017-04-20  141.22  142.92  141.16  142.44   23319562  1.76           1.0
2341 2017-04-21  142.44  142.68  141.85  142.27   17320928 -0.17          -1.0
2342 2017-04-24  143.50  143.95  143.18  143.64   17134333  1.37           1.0
2343 2017-04-25  143.91  144.90  143.87  144.53   18871501  0.89           1.0
2344 2017-04-26  144.47  144.60  143.38  143.68   20041241 -0.85          -1.0
2345 2017-04-27  143.92  144.16  143.31  143.79   14246347  0.11           1.0
2346 2017-04-28  144.09  144.30  143.27  143.65   20860358 -0.14          -1.0
2347 2017-05-01  145.10  147.20  144.96  146.58   33602943  2.93           1.0
2348 2017-05-02  147.54  148.09  146.84  147.51   45352194  0.93           1.0
2349 2017-05-03  145.59  147.49  144.27  147.06   45697034 -0.45          -1.0
2350 2017-05-04  146.52  147.14  145.81  146.53   23371872 -0.53          -1.0
2351 2017-05-05  146.76  148.98  146.76  148.96   27327725  2.43           1.0
2352 2017-05-08  149.03  153.70  149.03  153.01   48752413  4.05           1.0
2353 2017-05-09  153.87  154.88  153.45  153.99   39130363  0.98           1.0
2354 2017-05-10  153.63  153.94  152.11  153.26   25805692 -0.73          -1.0
2355 2017-05-11  152.45  154.07  152.31  153.95   27255058  0.69           1.0
2356 2017-05-12  154.70  156.42  154.67  156.10   32527017  2.15           1.0
2357 2017-05-15  156.01  156.65  155.05  155.70   26009719 -0.40          -1.0
2358 2017-05-16  155.94  156.06  154.72  155.47   20048478 -0.23          -1.0
2359 2017-05-17  153.60  154.57  149.71  150.25   50767678 -5.22          -1.0
2360 2017-05-18  151.27  153.34  151.13  152.54   33568215  2.29           1.0
2361 2017-05-19  153.38  153.98  152.63  153.06   26960788  0.52           1.0
2362 2017-05-22  154.00  154.58  152.91  153.99   22966437  0.93           1.0
2363 2017-05-23  154.90  154.90  153.31  153.80   19918871 -0.19          -1.0
2364 2017-05-24  153.84  154.17  152.67  153.34   19219154 -0.46          -1.0
2365 2017-05-25  153.73  154.35  153.03  153.87   19235598  0.53           1.0
2366 2017-05-26  154.00  154.24  153.31  153.61   21927637 -0.26          -1.0
2367 2017-05-30  153.42  154.43  153.33  153.67   20126851  0.06           1.0
2368 2017-05-31  153.97  154.17  152.38  152.76   24451164 -0.91          -1.0
2369 2017-06-01  153.17  153.33  152.22  153.18   16404088  0.42           1.0

[2370 rows x 8 columns]

In [205]:
AAPL_df['Date'] = AAPL_df['Date'].dt.date

In [206]:
pd.to_pickle(AAPL_df, '../predicting_stock_market_trends_with_Twitter/data/AAPL_df.pickle')